services:
  - type: web
    name: mss
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install pydantic-core==2.23.4 --only-binary :all:
      pip install pydantic==2.9.2 --only-binary :all:
      pip install -r requirements.txt
    startCommand: python main.py
